[package]
name = "rrule"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "rrule"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.19"
chrono-tz = "0.6.1"
rustler = "0.25.0"
rrule = "0.10.0"
