[package]
name = "rrule"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "rrule"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.40"
chrono-tz = "0.10.3"
rustler = "0.36.1"
rrule = "0.13.0"
